In [1]:
# https://allensdk.readthedocs.io/en/latest/_static/examples/nb/visual_behavior_neuropixels_dataset_manifest.html

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path

import allensdk
from allensdk.brain_observatory.behavior.behavior_project_cache.\
    behavior_neuropixels_project_cache \
    import VisualBehaviorNeuropixelsProjectCache

In [3]:
# Update this to a valid directory in your filesystem. This is where the data will be stored.
output_dir = "../data/"
cache = VisualBehaviorNeuropixelsProjectCache.from_s3_cache(
            cache_dir=Path(output_dir))

ecephys_sessions.csv:   0%|          | 0.00/64.4k [00:00<?, ?MB/s]
behavior_sessions.csv: 100%|██████████| 562k/562k [00:00<00:00, 671kMB/s]
units.csv: 100%|██████████| 134M/134M [01:37<00:00, 1.37MMB/s]
probes.csv: 100%|██████████| 130k/130k [00:00<00:00, 705kMB/s]
channels.csv: 100%|██████████| 27.9M/27.9M [00:16<00:00, 1.71MMB/s]

In [4]:
ecephys_sessions_table = cache.get_ecephys_session_table()
ecephys_sessions_table.columns

Index(['behavior_session_id', 'date_of_acquisition', 'equipment_name',
       'session_type', 'mouse_id', 'genotype', 'sex', 'project_code',
       'age_in_days', 'unit_count', 'probe_count', 'channel_count',
       'structure_acronyms', 'image_set', 'prior_exposures_to_image_set',
       'session_number', 'experience_level', 'prior_exposures_to_omissions',
       'file_id', 'abnormal_histology', 'abnormal_activity'],
      dtype='object')

In [5]:
ecephys_sessions_table

,behavior_session_id,date_of_acquisition,equipment_name,session_type,mouse_id,genotype,sex,project_code,age_in_days,unit_count,...,channel_count,structure_acronyms,image_set,prior_exposures_to_image_set,session_number,experience_level,prior_exposures_to_omissions,file_id,abnormal_histology,abnormal_activity
ecephys_session_id,,,,,,,,,,,,,,,,,,,,,
1044385384,1044408432,2020-08-19 14:47:08.574000+00:00,NP.1,EPHYS_1_images_G_5uL_reward,524761,wt/wt,F,NeuropixelVisualBehavior,151,2179,...,1920,"['CA1', 'CA3', 'DG-mo', 'DG-po', 'DG-sg', 'LGv...",G,30,1,Familiar,0,870,NaN,NaN
1044594870,1044624428,2020-08-20 15:03:56.422000+00:00,NP.1,EPHYS_1_images_H_5uL_reward,524761,wt/wt,F,NeuropixelVisualBehavior,152,2103,...,1920,"['CA1', 'CA3', 'DG-mo', 'DG-po', 'DG-sg', 'HPF...",H,0,2,Novel,1,872,NaN,NaN
1047969464,1048005547,2020-09-02 14:53:14.347000+00:00,NP.1,EPHYS_1_images_G_3uL_reward,509808,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,M,NeuropixelVisualBehavior,263,2438,...,2304,"['APN', 'CA1', 'CA3', 'DG-mo', 'DG-po', 'DG-sg...",G,62,1,Familiar,0,877,NaN,NaN
1047977240,1048009327,2020-09-02 15:15:03.733000+00:00,NP.0,EPHYS_1_images_G_3uL_reward,524925,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,F,NeuropixelVisualBehavior,165,1856,...,2304,"['APN', 'CA1', 'CA3', 'DG-mo', 'DG-po', 'DG-sg...",G,51,1,Familiar,0,878,NaN,NaN
1048189115,1048221709,2020-09-03 14:16:57.913000+00:00,NP.1,EPHYS_1_images_H_3uL_reward,509808,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,M,NeuropixelVisualBehavior,264,1925,...,2304,"['APN', 'CA1', 'CA3', 'DG-mo', 'DG-po', 'DG-sg...",H,0,2,Novel,1,879,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130349290,1130378962,2021-09-23 13:34:57.267000+00:00,NP.0,EPHYS_1_images_G_3uL_reward,579993,wt/wt,F,NeuropixelVisualBehavior,165,1928,...,2304,"['APN', 'CA1', 'CA3', 'DG-mo', 'DG-sg', 'HPF',...",G,0,2,Novel,1,1017,NaN,NaN
1139846596,1139969640,2021-11-10 15:08:35.544000+00:00,NP.1,EPHYS_1_images_H_3uL_reward,585329,wt/wt,M,NeuropixelVisualBehavior,175,2274,...,2304,"['APN', 'CA1', 'CA3', 'DG-mo', 'DG-po', 'DG-sg...",H,49,1,Familiar,0,1018,NaN,NaN
1140102579,1153972744,2021-11-11 14:09:15.377000+00:00,NP.1,EPHYS_1_images_G_3uL_reward,585329,wt/wt,M,NeuropixelVisualBehavior,176,1493,...,2304,"['APN', 'CA1', 'CA3', 'DG-mo', 'DG-po', 'DG-sg...",G,0,2,Novel,1,1019,NaN,NaN
1152632711,1152646832,2022-01-19 13:30:28.150000+00:00,NP.1,EPHYS_1_images_G_3uL_reward,599294,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,M,NeuropixelVisualBehavior,145,1499,...,2304,"['CA1', 'CA3', 'DG-mo', 'DG-po', 'DG-sg', 'HPF...",G,26,1,Familiar,0,1020,NaN,NaN
1152811536,1152845816,2022-01-20 13:50:22.372000+00:00,NP.1,EPHYS_1_images_H_3uL_reward,599294,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,M,NeuropixelVisualBehavior,146,1379,...,2304,"['CA1', 'CA3', 'DG-mo', 'DG-po', 'DG-sg', 'HPF...",H,0,2,Novel,1,1021,NaN,NaN

In [6]:
sessions_by_imageset_experience_day = ecephys_sessions_table.pivot_table(index=['session_number', 'experience_level'], 
                                                                        columns=['image_set'], 
                                                                        values='behavior_session_id', aggfunc=len)
display(sessions_by_imageset_experience_day)

image_set                           G     H
session_number experience_level
1              Familiar          38.0  10.0
               Novel              NaN   3.0
2              Familiar           3.0   NaN
               Novel             10.0  39.0

In [7]:
#Number of sessions per genotype/sex
sessions_by_genotype_sex = ecephys_sessions_table.pivot_table(values='session_number', index='genotype', 
                                                              columns='sex', aggfunc=len)
display(sessions_by_genotype_sex.rename(columns={'session_number': 'session_count'}))

sex                                             F   M
genotype
Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt  24  19
Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt   4  18
wt/wt                                          15  23

In [8]:
ecephys_sessions_no_filter = cache.get_ecephys_session_table(filter_abnormalities=False)
print(f'Number sessions returned by default: {len(ecephys_sessions_table)}')
print(f'Number of sessions returned without filtering abnormalities: {len(ecephys_sessions_no_filter)}')

Number sessions returned by default: 103
Number of sessions returned without filtering abnormalities: 153

In [9]:
behavior_sessions = cache.get_behavior_session_table()

print(f"Total number of behavior sessions: {len(behavior_sessions)}")

behavior_sessions.head()

Total number of behavior sessions: 3424

,equipment_name,genotype,mouse_id,sex,age_in_days,session_number,prior_exposures_to_session_type,prior_exposures_to_image_set,prior_exposures_to_omissions,ecephys_session_id,date_of_acquisition,session_type,image_set,file_id
behavior_session_id,,,,,,,,,,,,,,
1040882886,NP.1,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,506940,M,253,18,0,6,0,1040871931,2020-08-04 16:30:32.835000+00:00,HABITUATION_5_images_G_handoff_ready_5uL_reward,G,1022
1042886405,NP.0,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,506940,M,262,24,6,12,0,1042863451,2020-08-13 16:45:10.869000+00:00,HABITUATION_5_images_G_handoff_ready_5uL_reward,G,1023
1042328825,NP.0,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,506940,M,260,22,4,10,0,1042309765,2020-08-11 13:38:10.476000+00:00,HABITUATION_5_images_G_handoff_ready_5uL_reward,G,1024
1041062566,NP.1,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,506940,M,254,19,1,7,0,1041050914,2020-08-05 09:27:22.482000+00:00,HABITUATION_5_images_G_handoff_ready_5uL_reward,G,1025
1042578564,NP.0,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,506940,M,261,23,5,11,0,1042566236,2020-08-12 13:13:12.237000+00:00,HABITUATION_5_images_G_handoff_ready_5uL_reward,G,1026

In [10]:
print('there are', len(behavior_sessions.mouse_id.unique()), 'mice in the dataset')

there are 81 mice in the dataset

In [11]:
units = cache.get_unit_table()
print(f'This dataset contains {len(units)} total units')

units.head()

This dataset contains 319013 total units

,ecephys_channel_id,ecephys_probe_id,ecephys_session_id,amplitude_cutoff,anterior_posterior_ccf_coordinate,dorsal_ventral_ccf_coordinate,left_right_ccf_coordinate,cumulative_drift,d_prime,structure_acronym,...,valid_data,amplitude,waveform_duration,waveform_halfwidth,PT_ratio,recovery_slope,repolarization_slope,spread,velocity_above,velocity_below
unit_id,,,,,,,,,,,,,,,,,,,,,
1157005856,1157001834,1046469925,1046166369,0.500000,8453.0,3353.0,6719.0,140.32,6.088133,MB,...,True,143.066332,0.151089,0.096147,0.310791,-0.113863,0.480656,20.0,-0.457845,NaN
1157005853,1157001834,1046469925,1046166369,0.323927,8453.0,3353.0,6719.0,239.76,4.635583,MB,...,True,90.709418,0.357119,0.192295,0.531490,-0.075261,0.366371,30.0,2.060302,-2.060302
1157005720,1157001786,1046469925,1046166369,0.044133,8575.0,3842.0,6590.0,263.32,5.691955,MRN,...,True,90.433103,0.521943,0.178559,0.612217,-0.012119,0.269843,80.0,0.000000,0.863364
1157006074,1157001929,1046469925,1046166369,0.000583,8212.0,2477.0,6992.0,154.64,6.049284,NOT,...,True,287.492107,0.343384,0.192295,0.470194,-0.178335,1.129324,40.0,1.373534,0.000000
1157006072,1157001929,1046469925,1046166369,0.500000,8212.0,2477.0,6992.0,242.58,4.745499,NOT,...,True,157.897057,0.329648,0.164824,0.488276,-0.105005,0.660135,70.0,0.412060,0.343384

In [12]:
#grab the ecephys session id for one experiment; these session ids are the indices of the ecephys_sessions_table
session_id = ecephys_sessions_table.index.values[1]
session_units = units[units['ecephys_session_id']==session_id]
session_units.head()

,ecephys_channel_id,ecephys_probe_id,ecephys_session_id,amplitude_cutoff,anterior_posterior_ccf_coordinate,dorsal_ventral_ccf_coordinate,left_right_ccf_coordinate,cumulative_drift,d_prime,structure_acronym,...,valid_data,amplitude,waveform_duration,waveform_halfwidth,PT_ratio,recovery_slope,repolarization_slope,spread,velocity_above,velocity_below
unit_id,,,,,,,,,,,,,,,,,,,,,
1053043842,1053041745,1044791095,1044594870,0.500000,8921.0,3358.0,7602.0,294.86,4.335807,MRN,...,True,74.777722,0.357119,0.219765,0.567588,-0.065064,0.287071,120.0,0.529792,-1.079206
1053044108,1053041974,1044791095,1044594870,0.031346,9327.0,786.0,7877.0,0.00,3.455122,VISp,...,True,215.262889,0.604355,0.206030,0.408889,-0.067615,0.698667,70.0,0.961474,-0.137353
1053044102,1053041974,1044791095,1044594870,0.000429,9327.0,786.0,7877.0,5.84,5.424172,VISp,...,True,320.193557,0.645561,0.192295,0.405572,-0.123311,0.998621,70.0,0.755444,0.480737
1053044101,1053041974,1044791095,1044594870,0.025936,9327.0,786.0,7877.0,14.03,7.543906,VISp,...,True,296.918018,0.673032,0.206030,0.448527,-0.087712,0.484196,50.0,0.480737,0.686767
1053044067,1053041974,1044791095,1044594870,0.001713,9327.0,786.0,7877.0,154.46,4.693757,VISp,...,True,157.123005,0.274707,0.164824,0.562850,-0.138729,0.698068,50.0,0.000000,-0.343384

In [13]:
# Looks like we inserted all 6 probes during this experiment
session_probes_from_units_table = np.sort(session_units.ecephys_probe_id.unique())
print(f'We recorded from {len(session_probes_from_units_table)} probes this session')

We recorded from 5 probes this session

In [14]:
probes = cache.get_probe_table()
session_probes = probes[probes.ecephys_session_id==session_id].index.values
np.all(session_probes_from_units_table==session_probes)

True

In [15]:
channels = cache.get_channel_table()
channels.head()

,ecephys_probe_id,ecephys_session_id,probe_channel_number,probe_vertical_position,probe_horizontal_position,anterior_posterior_ccf_coordinate,dorsal_ventral_ccf_coordinate,left_right_ccf_coordinate,structure_acronym,unit_count,valid_data
ecephys_channel_id,,,,,,,,,,,
1049365509,1048089911,1047969464,0,20.0,43.0,8445.0,4013.0,6753.0,MRN,0,True
1049365511,1048089911,1047969464,1,20.0,11.0,8443.0,4005.0,6755.0,MRN,5,True
1049365512,1048089911,1047969464,2,40.0,59.0,8441.0,3997.0,6757.0,MRN,0,True
1049365513,1048089911,1047969464,3,40.0,27.0,8439.0,3989.0,6759.0,MRN,5,True
1049365514,1048089911,1047969464,4,60.0,43.0,8438.0,3981.0,6761.0,MRN,7,True